"""
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?
"""

# i + j = pentagon
# => pentagon - i = j

import functools
import math

@functools.lru_cache(maxsize=None)
def pentagon(n):
    return int(n * (3 * n - 1) / 2)

@functools.lru_cache(maxsize=None)
def is_pentagon(n):
    res = (math.sqrt(24 * n + 1) + 1) / 6
    return res.is_integer()

def find_d():
    i = 1
    while True:
        for j in range(i - 1, 0, -1):
            if is_pentagon(pentagon(i) + pentagon(j)) and \
               is_pentagon(pentagon(i) - pentagon(j)):
                return pentagon(i) - pentagon(j)
        i += 1

if __name__ == '__main__':
    print(find_d())
